language: ruby
cache: bundler
env:
  global:
    - CC_TEST_REPORTER_ID=aa9428ecce81885fa4f1c0d0283f0075e353dd1894ececefb103846e32794de3
  matrix:
    - DB=mysql
    - DB=postgres
services:
  - mysql
  - postgresql
rvm:
  - 2.5
  - 2.6
  - 2.7
before_install: gem install bundler --version '~> 1'
before_script:
  - cp config/database.yml.travis config/database.yml
  - 'echo "test: *${DB}" >> config/database.yml'
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rails spec
  - bundle exec rubocop
  - bundle exec haml-lint
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
